services:
  backend:
    build: ./BackEnd
    ports:
      - "80:3000"
    volumes:
      - ./FrontEnd/build/web:/usr/src/app/public
    environment:
      - NODE_ENV=production

  frontend:
    build: ./FrontEnd
    
