// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA431Cec-A4Zq2vvoxBzM3j7zXylJ1UNwI',
    appId: '1:549147796202:web:2f8dd5a3a973085b426d93',
    messagingSenderId: '549147796202',
    projectId: 'blackjack-80760',
    authDomain: 'blackjack-80760.firebaseapp.com',
    storageBucket: 'blackjack-80760.firebasestorage.app',
    measurementId: 'G-0BTTDWB1BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmZMOJqji80uraBd0NWjHUCdlajiNM60w',
    appId: '1:549147796202:android:22f2f4cba3ebf7c6426d93',
    messagingSenderId: '549147796202',
    projectId: 'blackjack-80760',
    storageBucket: 'blackjack-80760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4_JcKRy98_hBdl8DskheAfdtMBlPjgSU',
    appId: '1:549147796202:ios:24e8fc8b9c8ece0b426d93',
    messagingSenderId: '549147796202',
    projectId: 'blackjack-80760',
    storageBucket: 'blackjack-80760.firebasestorage.app',
    iosBundleId: 'com.example.blackjackProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4_JcKRy98_hBdl8DskheAfdtMBlPjgSU',
    appId: '1:549147796202:ios:24e8fc8b9c8ece0b426d93',
    messagingSenderId: '549147796202',
    projectId: 'blackjack-80760',
    storageBucket: 'blackjack-80760.firebasestorage.app',
    iosBundleId: 'com.example.blackjackProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA431Cec-A4Zq2vvoxBzM3j7zXylJ1UNwI',
    appId: '1:549147796202:web:f58bee5d49cf15fa426d93',
    messagingSenderId: '549147796202',
    projectId: 'blackjack-80760',
    authDomain: 'blackjack-80760.firebaseapp.com',
    storageBucket: 'blackjack-80760.firebasestorage.app',
    measurementId: 'G-LDFPSY0L00',
  );
}
